# Generated by Django 5.2.7 on 2026-01-03 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code'], 'verbose_name': '課程', 'verbose_name_plural': '課程'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '選課記錄', 'verbose_name_plural': '選課記錄'},
        ),
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=30, help_text='最大人數'),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3, help_text='學分數'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='課程描述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='課程代碼（唯一）', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='課程名稱', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(blank=True, help_text='授課教師（文字）', max_length=100),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, help_text='系別或部門', max_length=100)),
                ('office', models.CharField(blank=True, help_text='辦公室位置', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='聯絡電話', max_length=20)),
                ('office_hours', models.TextField(blank=True, help_text='辦公時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '教師',
                'verbose_name_plural': '教師',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_fk',
            field=models.ForeignKey(blank=True, help_text='授課教師（指定）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='grades.teacher'),
        ),
    ]
